// ============================================================
// FIREBASE CONFIGURATION
// ============================================================
// WEEK 3: Replace the placeholder values below with YOUR
// Firebase project config from:
//   Firebase Console > Project Settings > Your Apps > Web App
//
// DO NOT edit this file until Week 3 (Deliverable 3).
// ============================================================

import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyD_TMEndvIALEeHgy7g-lNvEmb8ap4YQVg",
  authDomain: "sagarmatha-restaurant.firebaseapp.com",
  projectId: "sagarmatha-restaurant",
  storageBucket: "sagarmatha-restaurant.firebasestorage.app",
  messagingSenderId: "503871916298",
  appId: "1:503871916298:web:cd33c097eedbb099c192f3"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Firestore and export it
export const db = getFirestore(app);
